name: CI/CD

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundler 2
        run: gem install bundler -v '~> 2.1.0' --no-document
      - name: Bundle install
        run: |
          set -x
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3 --without development
          bundle clean

      - name: RSpec
        run: bundle exec rspec --force-color
      - name: Rubocop
        run: bundle exec rubocop .
